version: "3"
services:
  app:  
    image: node:12-alpine
    container_name: phu-nodejs-posts
    restart: unless-stopped
    
    volumes:
      - ./:/myapp
    
    working_dir: /myapp
    
    #environment:
    #  NODE_ENV: development
    
    ports:
      - 6001:3000
    
    command: >
        sh -c "npm install -g nodemon && npm install && npm run start"
    #command: sh -c "npm install -g pm2 && npm install && pm2-runtime server.js --watch"
    #command: npm run start              
    #command: npm run dev
    
    #build:
    #  context: .
    #  dockerfile: Dockerfile.dev
    
    #install: 
    #  command: npm i

#  web-cli:
#    image: nodejs:12-alpine
#    container_name: phu-cli
#    command: /bin/sh
  